version: '3'
services:
  web:
    build: ./app
    ports:
      - "3000:80"
    networks:
      internal:

  server:
    build: ./server
    ports:
      - "4000:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - TZ=UTC
    networks:
      internal:
        aliases:
          - api
  mongo:
    image: "mongo:3.4"
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/data/db:/data/db
    networks:
      internal:
        aliases:
          - mongo

  mongo-express:
    image: "mongo-express:latest"
    ports:
      - 8081:8081
    networks:
      internal:

networks:
  internal:
